// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI.Models;

public partial class CheckIn
{
    public Guid CheckinId { get; set; }

    public Guid? GuestId { get; set; }

    public Guid? EventId { get; set; }

    public DateTime? CheckinTime { get; set; }

    public string CheckinMethod { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool? RowStatus { get; set; }

    public virtual Event Event { get; set; }

    public virtual Guest Guest { get; set; }
}